### ISSUE TITLE
Explain use of browser global in README

### ISSUE THREAD

**Issue by bengesoff** [webdriverio/gulp-webdriver#12]
I don't know if I'm just missing something but I couldn't see anywhere that tells you that the `browser` object is available inside the mocha tests. Found it in an external blog post instead!

**Comment by bengesoff** [comment]
maybe an example?

**Comment by christian-bromann** [comment]
Since the new v1 version of gulp-webdriver uses the wdio test runner I don't think this is necessary since all wdio example are using the `browser` object to do stuff. In fact it should be mentioned somewhere.
