### ISSUE TITLE
Task execution stuck on "start selenium standalone server"

### ISSUE THREAD

**Issue by dominikschreiber** [webdriverio/gulp-webdriver#13]
**tl;dr** gulp task is stuck on "start selenium standalone server" step, I'm asking for help. I blame the corporate proxy settings but am not sure about anything.

---

I use pretty much the code from the README example in my gulpfile:

``` javascript
// gulpfile.js
var gulp = require('gulp')
  , webdriver = require('gulp-webdriver');

gulp.task('test', function() {
  return gulp.src('*/*.spec.js', { read: false })
             .pipe(webdriver({
                  desiredCapabilities: { browserName: 'chrome' },
                  proxy: {
                      httpProxy: // my companies proxy here
                      sslProxy:   // same here
                  }
             });
});
```

As dependencies i have installed

```
// package.json, devDependencies section
"gulp": "^3.9.0",
"gulp-webdriver": "^0.1.1",
"mocha": "^2.2.5",
"webdriverio": "^3.1.0"
```

When I run `gulp test`, it gets stuck on the `start selenium standalone server` step:

``` bash
[08:57:00] {{ my workspace here }}\gulpfile.js
[08:57:00] Starting 'test'...
[08:57:00] run webdriverio with following capabilities: {"desiredCapabilities":{"browserName":"chrome"},"proxy":{"httpPr
oxy":"{{ my companies proxy here }}","sslProxy":"{{ and here }}"}}
[08:57:00] checking if selenium is running
[08:57:01] selenium is not running
[08:57:01] installing driver if needed
[08:57:02] driver installed
[08:57:02] start selenium standalone server
```

I'm on a windows (:disappointed:) 8.1. 64bit machine with `node -v` v0.12.7 and `npm -v` 2.11.3.

I'd expect the task to start the selenium server and run my specs. _What am I missing?_

**Comment by christian-bromann** [comment]
There reason for this issue is that gulp-webdriver 0.1.1 wasn't compatible with WebdriverIO v3.x. Please update to gulp-webdriver@v1.0.0 and you can use all new feature of WebdriverIO v3
