### ISSUE TITLE
I can't make it work with multiple browsers and capabilities

### ISSUE THREAD

**Issue by yuriy-yarosh** [webdriverio/gulp-webdriver#14]
I'm trying to start gulp-webdriver with following options:

```
{
    "desiredCapabilities": [{
        "browserName": "chrome",
        "chromeOptions": {
            "args": ["start-maximized", "show-fps-counter=true"],
            "prefs": {}
        },
        "javascriptEnabled": true,
        "databaseEnabled": true,
        "locationContextEnabled": true,
        "applicationCacheEnabled": true,
        "webStorageEnabled": true,
        "acceptSslCerts": true,
        "nativeEvents": true
    }],
    "host": "localhost",
    "port": "4444",
    "path": "/wd/hub",
    "logLevel": "verbose",
    "coloredLogs": true,
    "screenshotPath": "./reports/shots",
    "waitforTimeout": 2000,
    "slow": 75,
    "framework": "mocha",
    "ui": "bdd",
    "nospawn": false,
    "seleniumOptions": {},
    "seleniumInstallOptions": {
        "chrome": {
            "version": "2.18",
            "arch": "x64",
            "baseURL": "http://chromedriver.storage.googleapis.com"
        }
    },
    "reporter": "dot"
}
```

Which of course is failing

```
TypeError: Cannot read property 'chromeOptions' of undefined
    at /project/node_modules/gulp-webdriver/node_modules/deepmerge/index.js:40:28
    at Array.forEach (native)
    at deepmerge (/project/node_modules/gulp-webdriver/node_modules/deepmerge/index.js:35:26)
    at /project/node_modules/gulp-webdriver/node_modules/deepmerge/index.js:22:26
    at Array.forEach (native)
    at deepmerge (/project/node_modules/gulp-webdriver/node_modules/deepmerge/index.js:18:13)
    at new WebdriverIO (/project/node_modules/gulp-webdriver/node_modules/webdriverio/lib/webdriverio.js:42:32)
    at WebdriverIO.Chain (/project/node_modules/gulp-webdriver/node_modules/webdriverio/node_modules/chainit/index.js:6:17)
    at Object.remote (/project/node_modules/gulp-webdriver/node_modules/webdriverio/index.js:63:16)
    at Object.GulpWebdriverIO (/project/node_modules/gulp-webdriver/index.js:46:34)
```

If I'm trying to run it with `desiredCapabilities` as an object, not as an array - it works fine.
If I'm trying to pass capabilities as `capabilities` property array - it launches, but does not recognizes 'em at all, and fallbacks to firefox instead.

I don't want to start a bunch of webdriver gulp tasks simultaneously, 'cause I'll get really messy output.
I hope there is a way to make this work as intended.

I think there should be some array check for `deepcopy` in case someone passes an array instead of an object to `capabilities` / `desiredCapabilities`.

**Comment by joe-glasgow** [comment]
Having a little trouble with this aswell, would be awesome if the multiremote feature from webdriverio was  attached! http://webdriver.io/guide/usage/multiremote.html

**Comment by yuriy-yarosh** [comment]
@joe-glasgow, I'll fork this repo and rewrite some stuff, on my free time.
Feel free to contact me via Skype void.nugget or mail.

**Comment by christian-bromann** [comment]
@VoidNugget I guess this issue got obsolete with the new release where you define all your capabilities within the wdio.conf.js

@joe-glasgow multiremote should work if you have your capabilities defined like [this](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.multiremote.conf.js#L23-L34) in your wdio.conf.js

@VoidNugget what do you want to rewrite?

**Comment by yuriy-yarosh** [comment]
@christian-bromann, thanks. Yup, I've wanted to pass all opts to wdio directly. But I've missed that you've already did so in a new release. So, now I have no trouble with mutiremotes.

**Comment by christian-bromann** [comment]
\o/

**Comment by joe-glasgow** [comment]
Thanks for the help @christian-bromann  & @VoidNugget > mysterious "ERROR: Couldn't connect to selenium server" now appears when defining multiple capabilities as per the example 
![screen shot 2015-09-07 at 09 12 01](https://cloud.githubusercontent.com/assets/318666/9712144/8ab0ca0a-5540-11e5-9d09-2efe2025031b.png)

**Comment by joe-glasgow** [comment]
@christian-bromann @VoidNugget - ignore me, wrong JVM version! :flushed:
