### ISSUE TITLE
Jasmine support

### ISSUE THREAD

**Issue by travisperson** [webdriverio/gulp-webdriver#2]
Is there anything that would cause this not to be able to support Jasmine at some point down the road?

**Comment by christian-bromann** [comment]
No not at all. What do you think, would it make sense and is this a common thing to support two frameworks (Mocha and Jasmine)?

**Comment by travisperson** [comment]
I just saw the generic gulp-webdriver and was curious if Jasmine was going to be considered. It can be two different packages though, similar to what you did with grunt-webdriver, and grunt-webdriver-jasmine (now that I see those). Which at this point I'd assume is what would happen if jasmine was going to be supported.

**Comment by christian-bromann** [comment]
@travisperson yes I agree. A different project called `gulp-webdriver-jasmine` would make sense. Feel free to create that project. Closing the issue for now as this project only targets mocha users.
