### ISSUE TITLE
`gulp.src('wdio.conf.js').pipe(webdriver({...}))` does nothing

### ISSUE THREAD

**Issue by apiv** [webdriverio/gulp-webdriver#25]
I can't get gulp-webdriver to use my wdio.conf.js, as described in the README of this repository. I've been debugging this for a while, but I'm pretty stumped...

My task:

``` js
gulp.src('wdio.conf.js').pipe(webdriver({}))
```

It ignores my entire wdio.conf.js, which includes the paths to run, and says to run the tests in chrome. Here are the options selenium runs with from the gulp task:

``` json
{"desiredCapabilities":{"browserName":"firefox","version":"","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","requestOrigins":{"url":"http://webdriver.io","version":"2.4.5","name":"webdriverio"}}}
```

Since it doesn't have the paths defined in wdio.conf.js, it thinks there are 0 tests, and exits immediately.

I can run the tests from the cli with plain wdio just fine:

```
$ wdio wdio.conf.js
```

**Comment by hamishtaplin** [comment]
@apiv I guess you closed this because you figure out why? Experiencing the same thing here.
