### ISSUE TITLE
Cannot configure browsers

### ISSUE THREAD

**Issue by jtn-d** [webdriverio/gulp-webdriver#28]
```
gulp.task('test:e2e', function() {
    return gulp.src('wdio.conf.js').pipe(webdriver({
        capabilities: [{
            browserName: 'firefox'
        }],
        logLevel: 'verbose',
        waitforTimeout: 10000,
        reporter: 'spec'
    }));
});
```

When running the task "capabilities" is not applied instead config in wdio.conf.js is used.

**Comment by christian-bromann** [comment]
@jtn-d you can only overwrite stuff that is defined when you call `wdio --help`. I would recommend to create multiple wdio configs for that case
