### ISSUE TITLE
Release a new version with recent bug fixes.

### ISSUE THREAD

**Issue by philipwalton** [webdriverio/gulp-webdriver#29]
The [problem with the `wdio` binary](https://github.com/webdriverio/gulp-webdriver/pull/27) not being nested inside the local `node_modules` folder has been fixed but not released.

I spent a bit of time working on a fix and a PR before realizing the code I was going to check in had a merge conflict with master, and that the bug had already been fixed.

**Comment by christian-bromann** [comment]
Last release went out 2 days ago. Sorry for the delay. Next time just bug me until I publish the new version ;-)
