### ISSUE TITLE
Still cannot use pageObject to reference click();

### ISSUE THREAD

**Issue by jonyet** [webdriverio/gulp-webdriver#45]
as of wdio v.4.0.7, you can write code like this:

```
it('A user searches for "qa testing" and submits', function () {
  Home.searchBar.click();
  Home.searchBar.keys('qa testing');
  Home.searchButton.click();
});
```

i've updated the gulp-webdriver package to install v.4.0.7 for itself, rather than 4.0.5, yet i still get the same error as wdio < 4.0.5

```
selector needs to be typeof `string`
```

i would think this is a very easy fix, let me know if there is anything i can do or if you think i've missed something.

thanks!

**Comment by christian-bromann** [comment]
Sorry @jonyet this is not a gulp-webdriver specific error. Please fill an issue an provide your test code and maybe selenium logs. Thanks!
