### ISSUE TITLE
Error when starting session in chrome browser

### ISSUE THREAD

**Issue by Henne2806** [webdriverio/gulp-webdriver#50]
I've got this error, when i tried to start a test session in the local chrome browser.

`[10:04:37] Starting 'test-e2e:local'...`

`ERROR: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"6208.1","isDefault":true},"id":1,"name":"","origin":"://"}`
`chrome`
`Error: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"6208.1","isDefault":true},"id":1,"name":"","origin":"://"}`

`[10:04:47] 'test-e2e:local' errored after 9.56 s`
`[10:04:47] Error in plugin 'gulp-webdriver'`
`Message:
    wdio exited with code 1`

The gulp task:
`gulp.task('test-e2e:local', function() {
		return gulp.src('./wdio.local.conf.js').pipe(webdriver());
});`

Capabilities in the wdio.local.conf.js are only:
`capabilities: [{
		   browserName: 'chrome'
}]`

I used the latest gulp-webdriver version 2.0.2. Testing on Windows 10.
The same when i tried to start a session in Firefox.

Has anyone a solution?

**Comment by christian-bromann** [comment]
@Henne2806 this is a chromedriver issue. It is unable to start Chrome probably because the chromedriver doesn't support the Chrome version you have. Please update the it and it should be fine.
