### ISSUE TITLE
Npm v2.0.2 does not match the github v2.0.2

### ISSUE THREAD

**Issue by kevinlambert** [webdriverio/gulp-webdriver#53]
It seems the the code on npm does not match the code on github for v2.0.2.

The stream end event is not in the npm version.

`process.nextTick(() => stream.emit('end'))`

**Comment by christian-bromann** [comment]
@kevinlambert just rereleased the package. Please try again and let me know if the problem still exist.

**Comment by kevinlambert** [comment]
Looks good now. Added #54 which should prevent this in the future.
