### ISSUE TITLE
init plugin before call init()

### ISSUE THREAD

**Issue by ayxos** [webdriverio/gulp-webdriver#58]
Is there any way to embed a plugin before run webdriverio init() method through gulp?

I want to init this plugin (https://github.com/chmanie/webdriverajax) before start browser

**Comment by christian-bromann** [comment]
@ayxos you can use that plugin. Just add it to the plugin object as described [here](https://github.com/chmanie/webdriverajax#usage)

**Comment by ayxos** [comment]
Does not work. i have include it inside `wdio.conf.js` but `Cannot read property 'expectRequest' of undefined`
