### ISSUE TITLE
Replace gulp-util

### ISSUE THREAD

**Issue by Lukenickerson** [webdriverio/gulp-webdriver#64]
When installing with npm, we get the warning:

> npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

According to [this article](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) and the [gulp-util repo](https://github.com/gulpjs/gulp-util) we can see that gulp-util is deprecated. 
There are instructions in those links on how to replace gulp-util with specific, smaller modules.

I think the only thing that's used from gulp-util is `PluginError `, so this module could be used instead: https://www.npmjs.com/package/plugin-error

**Comment by christian-bromann** [comment]
@Lukenickerson I haven't been able to put much love into this package. Any contribution to it is highly appreciated. Thanks!

**Comment by jonn-set** [comment]
Removed references to `gulp-util`, please check the above pull request.

**Comment by christian-bromann** [comment]
Let's continue conversation in #69
