### ISSUE TITLE
Update gulp-webdriver to support webdriverIO version 5

### ISSUE THREAD

**Issue by kevinfox1** [webdriverio/gulp-webdriver#68]
gulp-webdriver is currently dependent on webdriverIO version 4. Please can this be updated so that this works with webdriverIO 5? Many thanks

**Comment by jonn-set** [comment]
I have updated and created a pull request #69, @christian-bromann can you review and if this is good enough please?

Thank you

**Comment by christian-bromann** [comment]
reviewed and merged
