### ISSUE TITLE
'output' option doesn't work

### ISSUE THREAD

**Issue by seb-b** [webdriverio/gulp-webdriver#7]
The readme mentions a 'output' options for piping reporter output. 
Doesn't look like it works and there's no reference to options.output in the source. 
(looks like the text for 'output' was copied straight from grunt-webdriver too)

**Comment by christian-bromann** [comment]
@seb-b good catch! You are right, output is not available in gulp-webdriver. Though it could get implemented. Feel free to open PR if you like :wink: 

Thanks
