### ISSUE TITLE
Plugin doesn't make use of new wdio.conf.js file

### ISSUE THREAD

**Issue by craig-jennings** [webdriverio/gulp-webdriver#9]
I've created a wdio.conf.js file to use for my testing, but it seems like this plugin doesn't make use of it. It'd be nice if I didn't have to duplicate my settings in the gulp task.

**Comment by christian-bromann** [comment]
This is exactly the plan for the next version: just reference the wdio.conf.js file and allow overwriting certain options.

**Comment by jopdeklein** [comment]
Isn't this already the working now? From the Readme:

```
gulp.task('test:e2e', function() {
    return gulp.src('wdio.conf.js').pipe(webdriver());
});
```

**Comment by craig-jennings** [comment]
@jopdeklein Looks like that fix dropped about 4 hours before your comment: 051bd74a7f1a8750de715905c3e1f0762b204444. I'll close this issue now.
